site_name: "linkml-rhea (ALPHA)"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Introduction: home.md
  - Schema: index.md
  - Credits: credits.md
site_url: https://chemkg.github.io/linkml-rhea/
repo_url: https://github.com/chemkg/linkml-rhea/
